/**
 * The balance suite: every bot, archetype and omen, summarised as markdown.
 */
import { DECKS, type DeckId } from '@/content/decks';
import type { Archetype } from '@/content/omamori';
import type { BotConfig } from './bots';
import { playRun, type RunSummary } from './driver';
import { summarise, type Summary } from './report';

interface Row {
  readonly label: string;
  readonly summary: Summary;
}

function batch(
  runs: number,
  bot: BotConfig,
  extra: { omen?: number; guided?: boolean; seed?: number; deckId?: DeckId } = {},
): Summary {
  const out: RunSummary[] = [];
  for (let i = 0; i < runs; i++) {
    out.push(
      playRun({
        seed: (extra.seed ?? 10_000) + i,
        bot,
        omen: extra.omen ?? 0,
        guided: extra.guided ?? false,
        ...(extra.deckId ? { deckId: extra.deckId } : {}),
      }),
    );
  }
  return summarise(out);
}

const pc = (x: number) => `${Math.round(x * 100)}%`;

export function runSuite(runs: number): string {
  const rows: Row[] = [];
  rows.push({ label: 'random bot', summary: batch(Math.min(runs, 200), { kind: 'random' }) });
  rows.push({ label: 'greedy bot (always stops)', summary: batch(runs, { kind: 'greedy' }) });
  rows.push({
    label: 'smart bot (auto archetype)',
    summary: batch(runs, { kind: 'smart', archetype: 'auto' }),
  });
  rows.push({
    label: 'smart bot, guided year',
    summary: batch(runs, { kind: 'smart', archetype: 'auto' }, { guided: true }),
  });
  const archetypes: Archetype[] = [
    'brights',
    'ribbons',
    'animals',
    'chaff',
    'greed',
    'sake',
    'season',
    'growth',
    'denial',
  ];
  const archRows: Row[] = archetypes.map((a) => ({
    label: a,
    summary: batch(runs, { kind: 'smart', archetype: a }),
  }));
  const deckRows: Row[] = DECKS.map((d) => ({
    label: d.name,
    summary: batch(runs, { kind: 'smart', archetype: 'auto' }, { deckId: d.id }),
  }));
  const omenRows: Row[] = [1, 2, 3, 4, 5].map((o) => ({
    label: `omen ${o}`,
    summary: batch(runs, { kind: 'smart', archetype: 'auto' }, { omen: o }),
  }));

  const md: string[] = [];
  md.push('# Balance report');
  md.push('');
  md.push(
    `Generated by \`pnpm sim --suite --runs ${runs}\`. Every number below comes from simulated runs.`,
  );
  md.push('');
  md.push('## Targets and verdict');
  md.push('');
  md.push(
    '- **Winnable:** a strong player (the smart bot) should clear the year about 45% of the time at Clear Sky. A player who never calls koi-koi should win less; a player who taps at random should never win.',
  );
  md.push(
    '- **Varied:** every archetype and every seasonal deck should be viable, within about 15 points of the best.',
  );
  md.push(
    '- **Tense:** fights last two to three hands, the bosses (months 3, 6, 9, 12) are the walls, and the final boss is the hardest fight of the year.',
  );
  md.push('- **Omens** should make each difficulty step clearly harder, ending in single digits.');
  md.push('');
  md.push('## Bots');
  md.push('');
  md.push('| Bot | Win rate | Avg month reached | Koi-koi per run | Exhausted hands |');
  md.push('| --- | --- | --- | --- | --- |');
  for (const r of rows) {
    md.push(
      `| ${r.label} | ${pc(r.summary.winRate)} | ${r.summary.avgMonthReached.toFixed(1)} | ${r.summary.koikoiPerRun.toFixed(1)} | ${pc(r.summary.exhaustedPerHand)} |`,
    );
  }
  md.push('');
  const main = rows[2]?.summary as Summary;
  md.push('## Month by month (smart bot, auto archetype)');
  md.push('');
  md.push(
    '| Month | Fights | Win | Hands/fight | HP at start | Damage taken | Player stop damage p25 / p50 / p90 | Spirit hit |',
  );
  md.push('| --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const m of main.months) {
    md.push(
      `| ${m.month} | ${m.fights} | ${pc(m.winRate)} | ${m.avgHands.toFixed(2)} | ${m.hpAtStart.toFixed(0)} | ${m.avgDamageTaken.toFixed(1)} | ${m.playerDamage.p25} / ${m.playerDamage.p50} / ${m.playerDamage.p90} | ${m.spiritHitAvg.toFixed(1)} |`,
    );
  }
  md.push('');
  md.push('## Archetypes (smart bot committed to one archetype)');
  md.push('');
  md.push('| Archetype | Win rate | Avg month reached |');
  md.push('| --- | --- | --- |');
  for (const r of archRows)
    md.push(`| ${r.label} | ${pc(r.summary.winRate)} | ${r.summary.avgMonthReached.toFixed(1)} |`);
  md.push('');
  md.push('## Seasonal decks (smart bot, auto archetype)');
  md.push('');
  md.push('| Deck | Win rate | Avg month reached |');
  md.push('| --- | --- | --- |');
  for (const r of deckRows)
    md.push(`| ${r.label} | ${pc(r.summary.winRate)} | ${r.summary.avgMonthReached.toFixed(1)} |`);
  md.push('');
  md.push('## Omens (difficulty)');
  md.push('');
  md.push('| Omen | Win rate | Avg month reached |');
  md.push('| --- | --- | --- |');
  md.push(`| 0 | ${pc(main.winRate)} | ${main.avgMonthReached.toFixed(1)} |`);
  for (const r of omenRows)
    md.push(
      `| ${r.label.replace('omen ', '')} | ${pc(r.summary.winRate)} | ${r.summary.avgMonthReached.toFixed(1)} |`,
    );
  md.push('');
  md.push('## Charms: win rate of runs that owned each charm (smart, auto)');
  md.push('');
  md.push('| Charm | Runs | Win rate |');
  md.push('| --- | --- | --- |');
  const charms = Object.entries(main.charmWinRate).sort(
    (a, b) => (b[1]?.winRate ?? 0) - (a[1]?.winRate ?? 0),
  );
  for (const [id, v] of charms) md.push(`| ${id} | ${v?.runs ?? 0} | ${pc(v?.winRate ?? 0)} |`);
  md.push('');
  md.push('## Yaku share of player stops (smart, auto)');
  md.push('');
  const ys = Object.entries(main.yakuShare).sort((a, b) => (b[1] ?? 0) - (a[1] ?? 0));
  md.push(ys.map(([k, v]) => `${k} ${pc(v ?? 0)}`).join(' · '));
  md.push('');
  return md.join('\n');
}
